"""empty message

Revision ID: c5103d67075d
Revises: 
Create Date: 2025-11-27 15:24:30.175481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5103d67075d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    op.create_table('messages',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('media_group_id', sa.BigInteger(), nullable=True),
    sa.Column('token_file', sa.String(), nullable=True),
    sa.Column('hash_tags', sa.String(), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index('ix_messages_hash_tags_trgm', 'messages', ['hash_tags'], unique=False, postgresql_using='gin', postgresql_ops={'hash_tags': 'gin_trgm_ops'})
    op.create_index(op.f('ix_messages_media_group_id'), 'messages', ['media_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_media_group_id'), table_name='messages')
    op.drop_index('ix_messages_hash_tags_trgm', table_name='messages', postgresql_using='gin', postgresql_ops={'hash_tags': 'gin_trgm_ops'})
    op.drop_table('messages')
    # ### end Alembic commands ###
